PRODUCT_VERSION_MAJOR = 2
PRODUCT_VERSION_MINOR = 8
PRODUCT_RELEASE_TYPE = ONEIRA_FINAL

LINEAGE_TARGET_PACKAGE_NAME ?= axion

include vendor/official_devices/infra/official_devices.mk

CURRENT_DEVICE := $(TARGET_DEVICE)
ifeq ($(CURRENT_DEVICE),)
CURRENT_DEVICE := $(patsubst lineage_%,%,$(TARGET_PRODUCT))
endif
AXION_OFFICIAL_DEVICE_MAINTAINERS := $(AXION_OFFICIAL_MAINTAINERS_$(CURRENT_DEVICE))

LINEAGE_BUILDTYPE ?= UNOFFICIAL

ifneq ($(AXION_MAINTAINER),)
ifneq ($(filter $(AXION_MAINTAINER),$(AXION_OFFICIAL_DEVICE_MAINTAINERS)),)
LINEAGE_BUILDTYPE := OFFICIAL
endif
endif

ifeq ($(LINEAGE_VERSION_APPEND_TIME_OF_DAY),true)
LINEAGE_BUILD_DATE := $(shell date -u +%Y%m%d%H%M%S)
else
LINEAGE_BUILD_DATE := $(shell date -u +%Y%m%d)
endif

ifeq ($(WITH_GMS),true)
TARGET_GAPPS_VARIANT ?= gms
ifeq ($(TARGET_GAPPS_VARIANT),pico)
AXION_BUILD_VARIANT := PICO
else ifeq ($(TARGET_GAPPS_VARIANT),core)
AXION_BUILD_VARIANT := CORE
else
AXION_BUILD_VARIANT := GMS
endif
else
AXION_BUILD_VARIANT := VANILLA
endif

LINEAGE_VERSION_SUFFIX := $(LINEAGE_BUILD_DATE)-$(AXION_BUILD_VARIANT)-$(LINEAGE_BUILD)

LINEAGE_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(PRODUCT_RELEASE_TYPE)-$(LINEAGE_VERSION_SUFFIX)

LINEAGE_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR)-$(LINEAGE_VERSION_SUFFIX)

PRODUCT_PRODUCT_PROPERTIES += \
    ro.axion.version=$(LINEAGE_VERSION) \
    ro.axion.display.version=$(LINEAGE_DISPLAY_VERSION) \
    ro.axion.build.version=$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)

PRODUCT_PRODUCT_PROPERTIES += \
    persist.sys.device_camera_info_rear=$(AXION_CAMERA_REAR_INFO) \
    persist.sys.device_camera_info_front=$(AXION_CAMERA_FRONT_INFO) \
    persist.sys.axion_maintainer=$(AXION_MAINTAINER) \
    persist.sys.axion_cpu_info=$(AXION_PROCESSOR)
